services:
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: .env
    environment:
      FLASK_APP: app.py
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5000
